<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>WinExe</OutputType>
    <MyType>WindowsForms</MyType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <OptionInfer>On</OptionInfer>
    <RemoveIntegerChecks>False</RemoveIntegerChecks>
    <OptionStrict>On</OptionStrict>
    <WarningLevel>4</WarningLevel>
    <DelaySign>False</DelaySign>
    <RunCodeAnalysis>False</RunCodeAnalysis>
    <RunSourceAnalysis>False</RunSourceAnalysis>
    <ApplicationIcon>My Project\iconApp.ico</ApplicationIcon>
    <IntermediateOutputPath>obj\$(Configuration)\</IntermediateOutputPath>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Title>Skye's Volume Display</Title>
    <Description>Master Volume Display With Minimalistic Interface &amp; Now Playing Info</Description>
    <AssemblyVersion>2.0</AssemblyVersion>
    <FileVersion>2.0</FileVersion>
    <StartupObject>SkyeVolume.My.MyApplication</StartupObject>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <ImportedNamespaces>Microsoft=False,System.Drawing=False,System.Windows.Forms=False,Microsoft.VisualBasic=True,System=True,System.Collections=True,System.Collections.Generic=True,System.Diagnostics=True,System.Linq=True,System.Xml.Linq=True,System.Threading.Tasks=True,SkyeVolume=True</ImportedNamespaces>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>DEBUG=1,TRACE=1</DefineConstants>
    <StartAction>Project</StartAction>
    <BaseAddress>4194304</BaseAddress>
    <RegisterForComInterop>False</RegisterForComInterop>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugType>None</DebugType>
    <DefineConstants>TRACE=1</DefineConstants>
    <BaseAddress>4194304</BaseAddress>
    <RegisterForComInterop>False</RegisterForComInterop>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DefineConstants>DEBUG=1,TRACE=1</DefineConstants>
    <FileAlignment>4096</FileAlignment>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DefineConstants>TRACE=1</DefineConstants>
    <FileAlignment>4096</FileAlignment>
    <DebugType>None</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="3.0.1" />
    <PackageReference Include="SkyeLibrary" Version="1.5.37" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="MainForm.Designer.vb">
      <DependentUpon>MainForm.vb</DependentUpon>
    </Compile>
    <Compile Update="Resources.Designer.vb">
      <DependentUpon>Resources.resx</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Settings.Designer.vb">
      <DependentUpon>Settings.vb</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Import Include="Microsoft" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.8">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.8 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Content Include="My Project\iconApp.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <PropertyGroup Condition=" '$(Platform)' == 'x86' ">
    <FileAlignment>4096</FileAlignment>
  </PropertyGroup>
</Project>